trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - group: 'Prod Management Resources'
  - name: buildConfiguration
    value: 'release'
  - name: buildPlatform
    value: 'any cpu'
  - name: DACPACSolutionBaseName
    value: SFA.DAS.Commitments.Database

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.2
    endpoint: SkillsFundingAgency

stages:
- stage: build
  displayName: Build Commitments 
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      SqlProjectPath: src/$(DACPACSolutionBaseName)/$(DACPACSolutionBaseName).sqlproj