trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: "release"
  buildPlatform: "anycpu"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

jobs:
  - job: 'CodeBuild'
    pool: 
      name: 'DAS - Continuous Integration'
    workspace:
      clean: all
    steps:
      - task: gittools.gitversion.gitversion-task.GitVersion@5
        displayName: GitVersion
        inputs:
          updateAssemblyInfo: true

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "src/**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: "src/**/*.csproj"
          arguments: "--configuration $(buildConfiguration) --no-restore"

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: "**/*Tests.csproj"
          arguments: "--configuration $(buildConfiguration) --no-build"

      - template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

      - task: DotNetCoreCLI@2
        displayName: "Publish API V1 "
        inputs:
          command: publish
          publishWebProjects: false
          projects: "src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build"

      - task: DotNetCoreCLI@2
        displayName: "Publish API V2"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/SFA.DAS.CommitmentsV2.Api.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build"

      - task: DotNetCoreCLI@2
        displayName: "Publish Web Job"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "src/CommitmentsV2/SFA.DAS.CommitmentsV2.Host/SFA.DAS.CommitmentsV2.Host.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build"

      - task: DotNetCoreCLI@2
        displayName: "Publish Support Site"
        inputs:
          command: publish
          publishWebProjects: false
          projects: "src/SFA.DAS.Commitments.Support.SubSite/SFA.DAS.Commitments.Support.SubSite.csproj"
          arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build"          
          
      - task: DotNetCoreCLI@2
        displayName: "dotnet pack"
        inputs:
          command: pack
          packagesToPack: >
            src/SFA.DAS.Commitments.Api.Client/SFA.DAS.Commitments.Api.Client.csproj
            src/SFA.DAS.Commitments.Api.Types/SFA.DAS.Commitments.Api.Types.csproj
            src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client/SFA.DAS.CommitmentsV2.Api.Client.csproj
            src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/SFA.DAS.CommitmentsV2.Api.Types.csproj
            src/CommitmentsV2/SFA.DAS.CommitmentsV2.Messages/SFA.DAS.CommitmentsV2.Messages.csproj
            src/CommitmentsV2/SFA.DAS.CommitmentsV2.Types/SFA.DAS.CommitmentsV2.Types.csproj
            src/CommitmentsV2/SFA.DAS.ReservationsV2.Api.Client/SFA.DAS.ReservationsV2.Api.Client.csproj
            src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared/SFA.DAS.CommitmentsV2.Shared.csproj
            src/SFA.DAS.Reservations.Api.Client/SFA.DAS.Reservations.Api.Client.csproj
            src/SFA.DAS.Reservations.API.Types/SFA.DAS.Reservations.Api.Types.csproj
            src/SFA.DAS.Reservations.Api.Client/SFA.DAS.Reservations.Api.Client.csproj
          packDirectory: "$(build.artifactstagingdirectory)/publish"
          versioningScheme: byBuildNumber
          buildProperties: 'Version="$(Build.BuildNumber)"'

      - task: CopyFiles@2
        displayName: "Copy Files to: $(build.artifactstagingdirectory)"
        inputs:
          contents: |
            azure/**
          targetFolder: "$(build.artifactstagingdirectory)/publish"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact"
        inputs:
          pathtoPublish: "$(build.artifactstagingdirectory)/publish"        