CREATE TABLE [dbo].[HistoryV2]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[TransactionId] UNIQUEIDENTIFIER NOT NULL,
	[EntityType] NVARCHAR(255) NOT NULL,
	[EntityState] NVARCHAR(8) NOT NULL,
	[Original] NVARCHAR(MAX) NULL,
	[Modified] NVARCHAR(MAX) NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL,
)
